### ISSUE TITLE
v-bind not working with button components

### ISSUE THREAD

**Issue by iorphx** [creativetimofficial/vue-argon-design-system#25]
`<base-button tag="a" :href="{{member.twitter}}" type="primary" icon="fab fa-twitter" rounded
 icon-only></base-button>`
this code throws error

`ERROR in ./pages/info/bandori.vue?vue&type=template&id=a52cddae& (./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./pages/info/bandori.vue?vue&type=template&id=a52cddae&)
Module build failed (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):
SyntaxError: Unexpected token (1:1312)
    at Parser.pp$4.raise (/var/www/seiyuu/node_modules/vue-template-es2015-compiler/buble.js:2757:13)
    at Parser.pp.unexpected (/var/www/seiyuu/node_modules/vue-template-es2015-compiler/buble.js:647:8)
    at Parser.pp$3.parseIdent (/var/www/seiyuu/node_modules/vue-template-es2015-compiler/buble.js:2712:10)
    at Parser.pp$3.parsePropertyName (/var/www/seiyuu/node_modules/vue-template-es2015-compiler/buble.js:2496:105)
    at Parser.pp$3.parseProperty (/var/www/seiyuu/node_modules/vue-template-es2015-compiler/buble.js:2426:8)
    at Parser.pp$3.parseObj (/var/www/seiyuu/node_modules/vue-template-es2015-compiler/buble.js:2380:23)
    at Parser.pp$3.parseExprAtom (/var/www/seiyuu/node_modules/vue-template-es2015-compiler/buble.js:2179:17)
    at Parser.<anonymous> (/var/www/seiyuu/node_modules/vue-template-es2015-compiler/buble.js:6003:24)
    at Parser.parseExprAtom (/var/www/seiyuu/node_modules/vue-template-es2015-compiler/buble.js:6129:31)
    at Parser.pp$3.parseExprSubscripts (/var/www/seiyuu/node_modules/vue-template-es2015-compiler/buble.js:2047:19)
    at Parser.pp$3.parseMaybeUnary (/var/www/seiyuu/node_modules/vue-template-es2015-compiler/buble.js:2024:17)
    at Parser.pp$3.parseExprOps (/var/www/seiyuu/node_modules/vue-template-es2015-compiler/buble.js:1966:19)
    at Parser.pp$3.parseMaybeConditional (/var/www/seiyuu/node_modules/vue-template-es2015-compiler/buble.js:1949:19)
    at Parser.pp$3.parseMaybeAssign (/var/www/seiyuu/node_modules/vue-template-es2015-compiler/buble.js:1925:19)
    at Parser.pp$3.parsePropertyValue (/var/www/seiyuu/node_modules/vue-template-es2015-compiler/buble.js:2443:87)
    at Parser.pp$3.parseProperty (/var/www/seiyuu/node_modules/vue-template-es2015-compiler/buble.js:2434:8)
    at Parser.pp$3.parseObj (/var/www/seiyuu/node_modules/vue-template-es2015-compiler/buble.js:2380:23)
    at Parser.pp$3.parseExprAtom (/var/www/seiyuu/node_modules/vue-template-es2015-compiler/buble.js:2179:17)
    at Parser.<anonymous> (/var/www/seiyuu/node_modules/vue-template-es2015-compiler/buble.js:6003:24)
    at Parser.parseExprAtom (/var/www/seiyuu/node_modules/vue-template-es2015-compiler/buble.js:6129:31)
    at Parser.pp$3.parseExprSubscripts (/var/www/seiyuu/node_modules/vue-template-es2015-compiler/buble.js:2047:19)
    at Parser.pp$3.parseMaybeUnary (/var/www/seiyuu/node_modules/vue-template-es2015-compiler/buble.js:2024:17)`

**Comment by iorphx** [comment]
never mind `<base-button tag="a" :href="member.twitter" type="primary" icon="fab fa-twitter" rounded icon-only></base-button>` works
