### ISSUE TITLE
No ESLint configuration found.

### ISSUE THREAD

**Issue by Manuel-Esmerio-Garcia** [creativetimofficial/vue-argon-design-system#34]
ERROR  Failed to compile with 1 errors                                                                                                           16:14:58
Module build failed (from ./node_modules/eslint-loader/index.js):
Error: No ESLint configuration found.
    at Config.getLocalConfigHierarchy (C:\Users\PC_Master_Race\Desktop\CheckItSuper\node_modules\eslint\lib\config.js:255:39)
    at Config.getConfigHierarchy (C:\Users\PC_Master_Race\Desktop\CheckItSuper\node_modules\eslint\lib\config.js:179:43)     
    at Config.getConfigVector (C:\Users\PC_Master_Race\Desktop\CheckItSuper\node_modules\eslint\lib\config.js:286:21)        
    at Config.getConfig (C:\Users\PC_Master_Race\Desktop\CheckItSuper\node_modules\eslint\lib\config.js:329:29)
    at processText (C:\Users\PC_Master_Race\Desktop\CheckItSuper\node_modules\eslint\lib\cli-engine.js:163:33)
    at CLIEngine.executeOnText (C:\Users\PC_Master_Race\Desktop\CheckItSuper\node_modules\eslint\lib\cli-engine.js:620:17)   
    at lint (C:\Users\PC_Master_Race\Desktop\CheckItSuper\node_modules\eslint-loader\index.js:278:17)
    at C:\Users\PC_Master_Race\Desktop\CheckItSuper\node_modules\loader-fs-cache\index.js:127:18
    at ReadFileContext.callback (C:\Users\PC_Master_Race\Desktop\CheckItSuper\node_modules\loader-fs-cache\index.js:31:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:238:13)

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.

**Comment by brightgems** [comment]
Just have same error. here is how to resolve:
setup eslint confg file using eslint
```
npm install eslint -g -D
eslint --init
```

**Comment by jerrychong25** [comment]
> Just have same error. here is how to resolve:
> setup eslint confg file using eslint
> 
> ```
> npm install eslint -g -D
> eslint --init
> ```

Encountered same error, thanks for your solution!

**Comment by adebayo-moses** [comment]
Thanks, this worked seamlessly.

**Comment by talented-full-dev** [comment]
But, I faced many problems in installing eslint modules.
